issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl

linters:
  enable:
    - asciicheck
    - dupl
    - forbidigo
    - goconst
    - gocritic
    - gofmt
    - goprintffuncname
    - gosec
    - gosimple
    - makezero
    - misspell
    - revive
    - whitespace

linters-settings:
    godot:
      exclude:
        - '@.+'

    revive:
      rules:
        - name: var-naming
          arguments: [[], ["ID", "URL"], [{skipPackageNameChecks=true}]]
        - name: early-return
          severity: warning
        - name: argument-limit
          severity: warning
          arguments: [4]
          disabled: true
        - name: context-as-argument
          severity: warning
          arguments:
            - allowTypesBefore: "*testing.T"
        - name: context-keys-type
          severity: warning
        - name: datarace
          severity: warning
        - name: defer
          severity: warning
          arguments:
            - [ "call-chain", "loop", "return"]
        - name: error-naming
          severity: warning
        - name: error-strings
          severity: warning
        - name: errorf
          severity: warning
        - name: if-return
          severity: warning
        - name: line-length-limit
          severity: warning
          disabled: true
          arguments: [ 120 ]
        - name: nested-structs
          severity: warning
          disabled: true
        - name: unreachable-code
          severity: warning
        - name: useless-break
          severity: warning
        - name: unused-parameter
          severity: warning
        - name: unexported-naming
          severity: warning
    dupl:
      threshold: 450