version: "3.9"

networks:
  default:
    driver: bridge

volumes:
  postgres-data:

services:
  api:
    image: xm-test-service:latest
    env_file:
      - .env
    ports:
      - "443:443"
    depends_on:
      - redis
      - postgres
    healthcheck:
      test: curl --fail https://${HTTP_HOST}:${HTTP_PORT}/api/v1/health || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s
    restart: always
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}
    volumes:
      - postgres-data:/var/lib/postgresql/data
