// Package view provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package view

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for CreateCompanyRequestType.
const (
	CreateCompanyRequestTypeCooperative        CreateCompanyRequestType = "Cooperative"
	CreateCompanyRequestTypeCorporations       CreateCompanyRequestType = "Corporations"
	CreateCompanyRequestTypeNonProfit          CreateCompanyRequestType = "NonProfit"
	CreateCompanyRequestTypeSoleProprietorship CreateCompanyRequestType = "Sole Proprietorship"
)

// Defines values for GetCompanyResponseDataType.
const (
	GetCompanyResponseDataTypeCooperative        GetCompanyResponseDataType = "Cooperative"
	GetCompanyResponseDataTypeCorporations       GetCompanyResponseDataType = "Corporations"
	GetCompanyResponseDataTypeNonProfit          GetCompanyResponseDataType = "NonProfit"
	GetCompanyResponseDataTypeSoleProprietorship GetCompanyResponseDataType = "Sole Proprietorship"
)

// Defines values for PatchCompanyRequestType.
const (
	Cooperative        PatchCompanyRequestType = "Cooperative"
	Corporations       PatchCompanyRequestType = "Corporations"
	NonProfit          PatchCompanyRequestType = "NonProfit"
	SoleProprietorship PatchCompanyRequestType = "Sole Proprietorship"
)

// AuthRequest defines model for AuthRequest.
type AuthRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	// JWT access token
	AccessToken *string `json:"access_token,omitempty"`

	// Token expiration time in seconds
	ExpiresIn *int `json:"expires_in,omitempty"`

	// Token type
	TokenType *string `json:"token_type,omitempty"`
}

// Request body for creating a new company
type CreateCompanyRequest struct {
	// Number of employees in the company
	AmountOfEmployees int `json:"amount_of_employees"`

	// Detailed description of the company
	Description *string `json:"description,omitempty"`

	// Name of the company (must be unique)
	Name string `json:"name"`

	// Indicates whether the company is officially registered
	Registered bool `json:"registered"`

	// Type of company
	Type CreateCompanyRequestType `json:"type"`
}

// Type of company
type CreateCompanyRequestType string

// DeleteCompanyRequest defines model for DeleteCompanyRequest.
type DeleteCompanyRequest = openapi_types.UUID

// GetCompanyRequest defines model for GetCompanyRequest.
type GetCompanyRequest = openapi_types.UUID

// GetCompanyResponse defines model for GetCompanyResponse.
type GetCompanyResponse struct {
	// Company details
	Data *struct {
		// Number of employees in the company
		AmountOfEmployees int `json:"amount_of_employees"`

		// Detailed description of the company
		Description *string `json:"description,omitempty"`

		// Unique identifier of the company
		Id openapi_types.UUID `json:"id"`

		// Name of the company
		Name string `json:"name"`

		// Indicates whether the company is officially registered
		Registered bool `json:"registered"`

		// Type of company
		Type GetCompanyResponseDataType `json:"type"`
	} `json:"data,omitempty"`
}

// Type of company
type GetCompanyResponseDataType string

// Request body for updating a company's details
type PatchCompanyRequest struct {
	// Number of employees in the company
	AmountOfEmployees *int `json:"amount_of_employees,omitempty"`

	// Detailed description of the company
	Description *string `json:"description,omitempty"`

	// Name of the company (must be unique)
	Name *string `json:"name,omitempty"`

	// Indicates whether the company is officially registered
	Registered *bool `json:"registered,omitempty"`

	// Type of company
	Type *PatchCompanyRequestType `json:"type,omitempty"`
}

// Type of company
type PatchCompanyRequestType string

// LoginJSONBody defines parameters for Login.
type LoginJSONBody = AuthRequest

// CreateCompanyJSONBody defines parameters for CreateCompany.
type CreateCompanyJSONBody = CreateCompanyRequest

// PatchCompanyJSONBody defines parameters for PatchCompany.
type PatchCompanyJSONBody = PatchCompanyRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginJSONBody

// CreateCompanyJSONRequestBody defines body for CreateCompany for application/json ContentType.
type CreateCompanyJSONRequestBody = CreateCompanyJSONBody

// PatchCompanyJSONRequestBody defines body for PatchCompany for application/json ContentType.
type PatchCompanyJSONRequestBody = PatchCompanyJSONBody
